databases:
  - name: example
    databaseName: example
    user: example

services:
  - type: web
    name: example
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: example
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
